### PR TITLE
Spring-Boot 2.2.6, Spring Cloud Hoxton.SR3 version upgrade.

### PR DESCRIPTION
**Pull request by aklemanovits**
#### Notable Changes
- Some Binder specific interfaces have been introduced in the newer version of Spring Cloud Stream. Just had to implement them in the given classes.  
- [JavaSerializationMessageConverter](https://docs.spring.io/spring-cloud-stream/docs/current/api/org/springframework/cloud/stream/converter/JavaSerializationMessageConverter.html) removed in 2.1, so I removed any links/tests from the project that requires it.
- The autoconfiguration requires a `ActiveMQConnectionFactory` bean, which can be configured via standard Spring Boot configuration, but only when the property  `spring.jms.cache.enabled=false` is set. Ref: [ArtemisConnectionFactoryConfiguration](https://github.com/spring-projects/spring-boot/blob/2.2.x/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/artemis/ArtemisConnectionFactoryConfiguration.java) (I'm guessing this strong type dependency can be removed, if a `ServerLocator` can be created somehow. If that's not possible, than the documentation should be updated with this required property.)

#### Tests
- Every tests run green, when run in itself.
- when running the `PartitionCapableBinderIT` tests, sometimes they all pass, sometimes a random one fails. Not sure why is that, guessing some kind of a race condition via the embeded mq.
- The same applies when i try to run a full maven build, everything fine except the **spring-cloud-starter-stream-artemis-it-partition** module.

### CODE REVIEW

**Comment by gytis** [comment]
Thank you for the PR @aklemanovits. I'll try to review it and look into the failing test shortly.

**Comment by gytis** [comment]
@aklemanovits see https://github.com/aklemanovits/spring-cloud-stream-binder-artemis/pull/1

**Comment by aklemanovits** [comment]
@gytis thank you for the quick response, i checked the pr and merged it.

**Comment by gytis** [comment]
Thanks @aklemanovits. I've tried the changes locally and they work fine. I'll merge this PR and will investigate the CI failure separately.

**Pull request merged**
